### ISSUE TITLE
RestClient::InternalServerError: 500 Internal Server Error

### ISSUE THREAD

**Issue by mulrich1234** [kjohnston/pgbackups-archive#54]
Hi,
  I really like this GEM and want to use it for my scheduled external backups to AWS.
Actually it runs in about 60% of the cases. Sometimes though it crashes and no backup is done.
I am not sure if this is a Heroku problem or something else.

I use:
- heroku/toolbelt/3.35.1 (i386-mingw32) ruby/1.9.3
- pgbackup:Archive -1.0.2
- Windows 7

To reproduce the issue I execute the pgbackups:archive command from my local maschine: **C:\>heroku run rake pgbackups:archive --trace --app my-archiverHerokuApp**

**The serverside log looks like this:**
2015-05-06T14:16:09.362259+00:00 heroku[run.7542]: State changed from starting to up
2015-05-06T14:16:09.575591+00:00 heroku[run.7542]: Awaiting client
2015-05-06T14:16:09.684460+00:00 heroku[run.7542]: Starting process with command `bundle exec rake pgbackups:archive --trace`
2015-05-06T14:18:28.456025+00:00 heroku[run.7542]: Process exited with status 1
2015-05-06T14:18:28.469804+00:00 heroku[run.7542]: State changed from up to complete

**The Client Side log looks like this:**
C:\>heroku run rake pgbackups:archive --trace --app my-archiverHerokuApp
Running `rake pgbackups:archive --trace` attached to terminal... up, run.7542
** Invoke pgbackups:archive (first_time)
** Execute pgbackups:archive
**----> long pause here!!  <-----**
rake aborted!
RestClient::InternalServerError: 500 Internal Server Error
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:852:in `start'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:55:in `block (2 levels) in http_get'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/helpers.rb:104:in `retry_on_exception'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:54:in `block in http_get'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:106:in `checking_client_version'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:53:in `http_get'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:20:in `transfers_get'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/command/pg_backups.rb:383:in `poll_transfer'
/app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-1.0.2/lib/pgbackups-archive/job.rb:37:in `capture'
/app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-1.0.2/lib/pgbackups-archive/job.rb:22:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-1.0.2/lib/pgbackups-archive/job.rb:12:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-1.0.2/lib/tasks/pgbackups_archive.rake:5:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/app/vendor/bundle/ruby/2.0.0/bin/rake:23:in `load'
/app/vendor/bundle/ruby/2.0.0/bin/rake:23:in `<main>'
Tasks: TOP => pgbackups:archive

**Here are the config:vars I set. (As DATABASE_URL is the default I didn't set "PGBACKUPS_DATABASE")**
PGBACKUPS_APP:                   my-backupappname
PGBACKUPS_AWS_ACCESS_KEY_ID:     <aws access key>
PGBACKUPS_AWS_SECRET_ACCESS_KEY: <aws secret key>
PGBACKUPS_BUCKET:                aws-bucket
PGBACKUPS_REGION:                us-east-1

I have no Idea of ruby but could it be a dead lock with a timeout issue?
If anyone could help it would be really great!

Regards,
   Matthias

**Comment by mulrich1234** [comment]
Just updated to version 1.0.3 of pgbackup:archive.
Still the same error, here the output I get if the plugin is run by the scheduler (no trace):

2015-05-06T16:00:20.892055+00:00 heroku[api]: Starting process with command `bundle exec rake pgbackups:archive && curl https://nosnch.in/basdfseg3` by scheduler@addons.heroku.com
2015-05-06T16:00:32.595250+00:00 heroku[scheduler.4770]: Starting process with command `bundle exec rake pgbackups:archive && curl https://nosnch.in/basdfseg3`
2015-05-06T16:00:33.166590+00:00 heroku[scheduler.4770]: State changed from starting to up
2015-05-06T16:02:45.426845+00:00 app[scheduler.4770]: RestClient::InternalServerError: 500 Internal Server Error
2015-05-06T16:02:45.425985+00:00 app[scheduler.4770]: rake aborted!
2015-05-06T16:02:45.427248+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
2015-05-06T16:02:45.427250+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
2015-05-06T16:02:45.427252+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
2015-05-06T16:02:45.427253+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
2015-05-06T16:02:45.427254+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
2015-05-06T16:02:45.427255+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
2015-05-06T16:02:45.427256+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
2015-05-06T16:02:45.427259+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:55:in `block (2 levels) in http_get'
2015-05-06T16:02:45.427260+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/helpers.rb:104:in `retry_on_exception'
2015-05-06T16:02:45.427261+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:54:in `block in http_get'
2015-05-06T16:02:45.427263+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:106:in `checking_client_version'
2015-05-06T16:02:45.427264+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:53:in `http_get'
2015-05-06T16:02:45.427265+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/client/heroku_postgresql_backups.rb:20:in `transfers_get'
2015-05-06T16:02:45.427266+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/heroku-3.32.0/lib/heroku/command/pg_backups.rb:383:in `poll_transfer'
2015-05-06T16:02:45.427267+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-1.0.3/lib/pgbackups-archive/job.rb:37:in `capture'
2015-05-06T16:02:45.427269+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-1.0.3/lib/pgbackups-archive/job.rb:22:in `call'
2015-05-06T16:02:45.427270+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-1.0.3/lib/pgbackups-archive/job.rb:12:in `call'
2015-05-06T16:02:45.427271+00:00 app[scheduler.4770]: /app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-1.0.3/lib/tasks/pgbackups_archive.rake:5:in `block (2 levels) in <top (required)>'
2015-05-06T16:02:45.427275+00:00 app[scheduler.4770]: Tasks: TOP => pgbackups:archive
2015-05-06T16:02:45.427299+00:00 app[scheduler.4770]: (See full trace by running task with --trace)
2015-05-06T16:02:46.187329+00:00 heroku[scheduler.4770]: Process exited with status 1
2015-05-06T16:02:46.199463+00:00 heroku[scheduler.4770]: State changed from up to complete

**Comment by kjohnston** [comment]
I've seen this before, but it's been a while.  It seems like Heroku goes through periods of time where backups can't be captured (due to load?).  I haven't had this issue in a while but when I was able to produce it before it was when I was dealing with a ~1GB database and hitting the capture action repetitiously.  There was some speculation at the time that scheduling backups too closely together (for more sizable databases?) could cause more executions to fail during those periods of time, but this is just speculation.  How big is your database and how often does the task run?

**Comment by mulrich1234** [comment]
hm, the database is only 8MB and the backup runs once per day.
This shouldn't be too much of a problem.

**Comment by kjohnston** [comment]
Yeah, that size and frequency shouldn't be a problem.

Above you listed using `--app my-archiverHerokuApp` with the rake task and specifying `PGBACKUPS_APP: my-backupappname` as an env var.  Are you running a separate Heroku app to target a backup of the primary app?  If so, PGBACKUPS_APP needs to be set to the Heroku app name of the primary app.

`pgbackups-archive/job.rb: line 37` enqueues (and follows) a backup capture operation through the gem to the magical Heroku PGBackups API that isn't otherwise exposed to us.

The long pause kind of makes sense.  I see this to differing degrees and believe it's just related to the PGBackups service's load.  You should, however, see progress detail in the fashion below once it starts capturing:

```
~/path/to/repo > bundle exec heroku run rake pgbackups:archive -a appname
Running `rake pgbackups:archive` attached to terminal... up, run.6523
** Invoke pgbackups:archive (first_time)
** Execute pgbackups:archive
Running... 0.00B
```

The "Running... 0.00B" is updated with size progress then replaced with:

```
Backup completed
Backup archived
```

**Comment by mulrich1234** [comment]
You are right. I have a Java App (X) which has the db I want to backup.
The other App (Y) containes the pgbackups:archive gem.
In App Y I actually set the Variable PGBACKUPS_APP to the name of App X.
I guess the general setup should be correct as it does not fail all the time...

I do see the output as you mention it when the backup runs successfull.

Do you think it might be more successfull to backup the follower DB of App X perhaps?

**Comment by mulrich1234** [comment]
here the output when it works:
`C:\>heroku run rake pgbackups:archive --trace --app my-archiver`
`Running 'rake pgbackups:archive --trace' attached to terminal... up, run.3404`
`** Invoke pgbackups:archive (first_time)`
`** Execute pgbackups:archive`
`←[0KRunning... 2.10MB`

after its done:
`** Invoke pgbackups:archive (first_time)`
`** Execute pgbackups:archive`
`←[0KBackup completedB`
`Backup archived`

**Comment by kjohnston** [comment]
Since you're targeting a different app to backup, you need to set PGBACKUPS_DATABASE to the URL of the database you want to backup (otherwise it'll default to DATABASE_URL of the app your running the rake task from).  Since you're using a follower, use its URL, that way you don't hinder your app's performance or the pg_dump task's performance.

**Comment by mulrich1234** [comment]
Thanks a lot. I now use the url of the follower, it seems to run smoothly now.
You definitly got a point with the DATABASE_URL thing, stupid me!

Consider the issue closed. Thanks for the help!!!

**Comment by kjohnston** [comment]
No problem.  Glad to hear things are looking good.  Cheers.
